# Site settings
title: Instituto Pedagógico Comenio - Departamento de Actividades Extracurriculares.
# description: 'Descripción de actividades realizadas en el LID con los estudiantes del IPC'
description: 'En el Instituto Pedagógico Comenio, creemos en una educación integral que va más allá de las aulas. Nuestras materias extracurriculares —Inglés, Danza y Música— son pilares fundamentales para el desarrollo de habilidades cognitivas, emocionales y sociales en nuestros pequeños.'
url: 'https://ipc-extras.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Ing. Gerardo Galileo Reyes'
  email: gerardogalileo.reyes.ce32@dgeti.sems.gob.mx
#  twitter_username: joshgerdes
#  facebook_username: joshgerdes
#  github_username:  joshgerdes
#  linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
